version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  aws-parameter-store: circleci/aws-parameter-store@1.0.0
jobs:
  buildapp:
    docker:
      - image: cimg/node:12.18.0
    steps:
      - checkout
      - run: npm ci
      - store_test_results:
          path: "coverage"
      - store_artifacts:
          path: "coverage"
      - persist_to_workspace:
          root: ~/
          paths:
            - .
  deploy_dev:
    docker:
      - image: cimg/node:12.18.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c8:88:a1:a9:a2:2b:33:fd:a4:e4:85:4d:a3:96:3b:0b"
      - attach_workspace:
          at: .
      - run: cd project; bash ./deploy-dev.sh
  deploy_marketing:
    docker:
      - image: circleci/python
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/.
      - run:
          name: Install awscli
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$DEMO_AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$DEMO_AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run: sh ./prepare-demo.sh
      - run: zip app.zip -r --symlinks * .[^.]*
      - run: eb deploy --staged
      - slack/status

workflows:
  testdiego:
    jobs:
      - buildapp
      - deploy_dev:
          requires:
            - buildapp
          filters:
            branches:
              only: master
      - deploy_marketing:
          requires:
            - buildapp
          filters:
            branches:
              only: marketing

